PYTORCH_CKPT_MAPPING = {'text_encoder': [('cond_stage_model.transformer.text_model.embeddings.token_embedding.weight',
   None),
  ('cond_stage_model.transformer.text_model.embeddings.position_embedding.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.layer_norm1.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.layer_norm1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.q_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.q_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.k_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.k_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.v_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.v_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.out_proj.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.out_proj.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.layer_norm2.weight',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.layer_norm2.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc1.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc1.bias',
   None),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc2.weight',
   (1, 0)),
  ('cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc2.bias',
   None),
  ('cond_stage_model.transformer.text_model.final_layer_norm.weight', None),
  ('cond_stage_model.transformer.text_model.final_layer_norm.bias', None)],
 'diffusion_model': [('model.diffusion_model.time_embed.0.weight', (1, 0)),
  ('model.diffusion_model.time_embed.0.bias', None),
  ('model.diffusion_model.time_embed.2.weight', (1, 0)),
  ('model.diffusion_model.time_embed.2.bias', None),
  ('model.diffusion_model.input_blocks.0.0.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.0.0.bias', None),
  ('model.diffusion_model.input_blocks.1.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.1.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.1.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.1.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.1.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.1.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.1.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.1.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.1.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.1.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.1.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.1.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.1.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.1.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.1.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.1.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.2.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.2.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.2.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.2.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.2.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.2.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.2.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.2.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.2.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.2.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.2.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.2.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.2.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.2.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.2.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.2.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.3.0.op.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.3.0.op.bias', None),
  ('model.diffusion_model.input_blocks.4.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.4.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.4.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.4.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.4.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.4.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.4.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.4.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.4.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.4.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.4.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.4.0.skip_connection.bias', None),
  ('model.diffusion_model.input_blocks.4.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.4.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.4.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.4.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.4.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.4.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.5.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.5.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.5.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.5.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.5.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.5.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.5.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.5.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.5.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.5.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.5.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.5.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.5.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.5.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.5.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.5.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.6.0.op.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.6.0.op.bias', None),
  ('model.diffusion_model.input_blocks.7.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.7.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.7.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.7.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.7.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.7.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.7.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.7.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.7.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.7.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.7.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.7.0.skip_connection.bias', None),
  ('model.diffusion_model.input_blocks.7.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.7.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.7.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.7.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.7.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.7.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.8.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.8.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.8.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.8.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.8.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.8.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.8.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.8.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.8.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.8.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.8.1.norm.weight', None),
  ('model.diffusion_model.input_blocks.8.1.norm.bias', None),
  ('model.diffusion_model.input_blocks.8.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.8.1.proj_in.bias', None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.input_blocks.8.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.8.1.proj_out.bias', None),
  ('model.diffusion_model.input_blocks.9.0.op.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.9.0.op.bias', None),
  ('model.diffusion_model.input_blocks.10.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.10.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.10.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.10.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.10.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.10.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.10.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.10.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.10.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.10.0.out_layers.3.bias', None),
  ('model.diffusion_model.input_blocks.11.0.in_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.11.0.in_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.11.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.11.0.in_layers.2.bias', None),
  ('model.diffusion_model.input_blocks.11.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.input_blocks.11.0.emb_layers.1.bias', None),
  ('model.diffusion_model.input_blocks.11.0.out_layers.0.weight', None),
  ('model.diffusion_model.input_blocks.11.0.out_layers.0.bias', None),
  ('model.diffusion_model.input_blocks.11.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.input_blocks.11.0.out_layers.3.bias', None),
  ('model.diffusion_model.middle_block.0.in_layers.0.weight', None),
  ('model.diffusion_model.middle_block.0.in_layers.0.bias', None),
  ('model.diffusion_model.middle_block.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.0.in_layers.2.bias', None),
  ('model.diffusion_model.middle_block.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.middle_block.0.emb_layers.1.bias', None),
  ('model.diffusion_model.middle_block.0.out_layers.0.weight', None),
  ('model.diffusion_model.middle_block.0.out_layers.0.bias', None),
  ('model.diffusion_model.middle_block.0.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.0.out_layers.3.bias', None),
  ('model.diffusion_model.middle_block.1.norm.weight', None),
  ('model.diffusion_model.middle_block.1.norm.bias', None),
  ('model.diffusion_model.middle_block.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.1.proj_in.bias', None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.middle_block.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.1.proj_out.bias', None),
  ('model.diffusion_model.middle_block.2.in_layers.0.weight', None),
  ('model.diffusion_model.middle_block.2.in_layers.0.bias', None),
  ('model.diffusion_model.middle_block.2.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.2.in_layers.2.bias', None),
  ('model.diffusion_model.middle_block.2.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.middle_block.2.emb_layers.1.bias', None),
  ('model.diffusion_model.middle_block.2.out_layers.0.weight', None),
  ('model.diffusion_model.middle_block.2.out_layers.0.bias', None),
  ('model.diffusion_model.middle_block.2.out_layers.3.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.middle_block.2.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.0.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.0.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.0.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.0.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.0.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.0.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.0.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.0.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.0.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.0.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.0.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.0.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.1.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.1.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.1.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.1.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.1.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.1.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.1.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.1.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.1.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.1.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.1.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.1.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.2.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.2.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.2.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.2.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.2.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.2.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.2.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.2.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.2.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.2.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.2.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.2.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.2.1.conv.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.2.1.conv.bias', None),
  ('model.diffusion_model.output_blocks.3.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.3.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.3.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.3.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.3.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.3.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.3.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.3.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.3.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.3.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.3.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.3.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.3.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.3.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.3.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.3.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.3.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.3.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.4.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.4.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.4.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.4.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.4.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.4.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.4.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.4.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.4.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.4.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.4.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.4.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.4.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.4.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.4.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.4.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.4.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.4.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.5.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.5.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.5.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.5.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.5.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.5.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.5.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.5.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.5.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.5.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.5.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.5.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.5.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.5.2.conv.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.5.2.conv.bias', None),
  ('model.diffusion_model.output_blocks.6.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.6.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.6.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.6.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.6.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.6.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.6.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.6.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.6.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.6.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.6.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.6.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.6.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.6.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.6.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.6.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.6.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.6.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.7.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.7.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.7.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.7.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.7.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.7.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.7.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.7.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.7.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.7.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.7.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.7.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.7.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.7.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.7.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.7.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.7.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.7.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.8.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.8.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.8.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.8.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.8.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.8.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.8.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.8.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.8.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.8.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.8.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.8.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.8.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.8.2.conv.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.8.2.conv.bias', None),
  ('model.diffusion_model.output_blocks.9.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.9.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.9.0.in_layers.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.9.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.9.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.9.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.9.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.9.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.9.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.9.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.9.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.9.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.9.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.9.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.9.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.9.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.9.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.9.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.10.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.10.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.10.0.in_layers.2.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.10.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.10.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.10.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.10.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.10.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.10.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.10.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.10.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.10.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.10.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.10.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.10.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.10.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.10.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.10.1.proj_out.bias', None),
  ('model.diffusion_model.output_blocks.11.0.in_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.11.0.in_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.11.0.in_layers.2.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.11.0.in_layers.2.bias', None),
  ('model.diffusion_model.output_blocks.11.0.emb_layers.1.weight', (1, 0)),
  ('model.diffusion_model.output_blocks.11.0.emb_layers.1.bias', None),
  ('model.diffusion_model.output_blocks.11.0.out_layers.0.weight', None),
  ('model.diffusion_model.output_blocks.11.0.out_layers.0.bias', None),
  ('model.diffusion_model.output_blocks.11.0.out_layers.3.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.11.0.out_layers.3.bias', None),
  ('model.diffusion_model.output_blocks.11.0.skip_connection.weight',
   (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.11.0.skip_connection.bias', None),
  ('model.diffusion_model.output_blocks.11.1.norm.weight', None),
  ('model.diffusion_model.output_blocks.11.1.norm.bias', None),
  ('model.diffusion_model.output_blocks.11.1.proj_in.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.11.1.proj_in.bias', None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.weight',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.weight',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_q.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.weight',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.weight',
   (1, 0)),
  ('model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.bias',
   None),
  ('model.diffusion_model.output_blocks.11.1.proj_out.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.output_blocks.11.1.proj_out.bias', None),
  ('model.diffusion_model.out.0.weight', None),
  ('model.diffusion_model.out.0.bias', None),
  ('model.diffusion_model.out.2.weight', (2, 3, 1, 0)),
  ('model.diffusion_model.out.2.bias', None)],
 'decoder': [('first_stage_model.post_quant_conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.post_quant_conv.bias', None),
  ('first_stage_model.decoder.conv_in.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.conv_in.bias', None),
  ('first_stage_model.decoder.mid.block_1.norm1.weight', None),
  ('first_stage_model.decoder.mid.block_1.norm1.bias', None),
  ('first_stage_model.decoder.mid.block_1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.block_1.conv1.bias', None),
  ('first_stage_model.decoder.mid.block_1.norm2.weight', None),
  ('first_stage_model.decoder.mid.block_1.norm2.bias', None),
  ('first_stage_model.decoder.mid.block_1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.block_1.conv2.bias', None),
  ('first_stage_model.decoder.mid.attn_1.norm.weight', None),
  ('first_stage_model.decoder.mid.attn_1.norm.bias', None),
  ('first_stage_model.decoder.mid.attn_1.q.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.attn_1.q.bias', None),
  ('first_stage_model.decoder.mid.attn_1.k.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.attn_1.k.bias', None),
  ('first_stage_model.decoder.mid.attn_1.v.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.attn_1.v.bias', None),
  ('first_stage_model.decoder.mid.attn_1.proj_out.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.attn_1.proj_out.bias', None),
  ('first_stage_model.decoder.mid.block_2.norm1.weight', None),
  ('first_stage_model.decoder.mid.block_2.norm1.bias', None),
  ('first_stage_model.decoder.mid.block_2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.block_2.conv1.bias', None),
  ('first_stage_model.decoder.mid.block_2.norm2.weight', None),
  ('first_stage_model.decoder.mid.block_2.norm2.bias', None),
  ('first_stage_model.decoder.mid.block_2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.mid.block_2.conv2.bias', None),
  ('first_stage_model.decoder.up.3.block.0.norm1.weight', None),
  ('first_stage_model.decoder.up.3.block.0.norm1.bias', None),
  ('first_stage_model.decoder.up.3.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.0.conv1.bias', None),
  ('first_stage_model.decoder.up.3.block.0.norm2.weight', None),
  ('first_stage_model.decoder.up.3.block.0.norm2.bias', None),
  ('first_stage_model.decoder.up.3.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.0.conv2.bias', None),
  ('first_stage_model.decoder.up.3.block.1.norm1.weight', None),
  ('first_stage_model.decoder.up.3.block.1.norm1.bias', None),
  ('first_stage_model.decoder.up.3.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.1.conv1.bias', None),
  ('first_stage_model.decoder.up.3.block.1.norm2.weight', None),
  ('first_stage_model.decoder.up.3.block.1.norm2.bias', None),
  ('first_stage_model.decoder.up.3.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.1.conv2.bias', None),
  ('first_stage_model.decoder.up.3.block.2.norm1.weight', None),
  ('first_stage_model.decoder.up.3.block.2.norm1.bias', None),
  ('first_stage_model.decoder.up.3.block.2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.2.conv1.bias', None),
  ('first_stage_model.decoder.up.3.block.2.norm2.weight', None),
  ('first_stage_model.decoder.up.3.block.2.norm2.bias', None),
  ('first_stage_model.decoder.up.3.block.2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.block.2.conv2.bias', None),
  ('first_stage_model.decoder.up.3.upsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.3.upsample.conv.bias', None),
  ('first_stage_model.decoder.up.2.block.0.norm1.weight', None),
  ('first_stage_model.decoder.up.2.block.0.norm1.bias', None),
  ('first_stage_model.decoder.up.2.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.0.conv1.bias', None),
  ('first_stage_model.decoder.up.2.block.0.norm2.weight', None),
  ('first_stage_model.decoder.up.2.block.0.norm2.bias', None),
  ('first_stage_model.decoder.up.2.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.0.conv2.bias', None),
  ('first_stage_model.decoder.up.2.block.1.norm1.weight', None),
  ('first_stage_model.decoder.up.2.block.1.norm1.bias', None),
  ('first_stage_model.decoder.up.2.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.1.conv1.bias', None),
  ('first_stage_model.decoder.up.2.block.1.norm2.weight', None),
  ('first_stage_model.decoder.up.2.block.1.norm2.bias', None),
  ('first_stage_model.decoder.up.2.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.1.conv2.bias', None),
  ('first_stage_model.decoder.up.2.block.2.norm1.weight', None),
  ('first_stage_model.decoder.up.2.block.2.norm1.bias', None),
  ('first_stage_model.decoder.up.2.block.2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.2.conv1.bias', None),
  ('first_stage_model.decoder.up.2.block.2.norm2.weight', None),
  ('first_stage_model.decoder.up.2.block.2.norm2.bias', None),
  ('first_stage_model.decoder.up.2.block.2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.block.2.conv2.bias', None),
  ('first_stage_model.decoder.up.2.upsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.2.upsample.conv.bias', None),
  ('first_stage_model.decoder.up.1.block.0.norm1.weight', None),
  ('first_stage_model.decoder.up.1.block.0.norm1.bias', None),
  ('first_stage_model.decoder.up.1.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.0.conv1.bias', None),
  ('first_stage_model.decoder.up.1.block.0.norm2.weight', None),
  ('first_stage_model.decoder.up.1.block.0.norm2.bias', None),
  ('first_stage_model.decoder.up.1.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.0.conv2.bias', None),
  ('first_stage_model.decoder.up.1.block.0.nin_shortcut.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.0.nin_shortcut.bias', None),
  ('first_stage_model.decoder.up.1.block.1.norm1.weight', None),
  ('first_stage_model.decoder.up.1.block.1.norm1.bias', None),
  ('first_stage_model.decoder.up.1.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.1.conv1.bias', None),
  ('first_stage_model.decoder.up.1.block.1.norm2.weight', None),
  ('first_stage_model.decoder.up.1.block.1.norm2.bias', None),
  ('first_stage_model.decoder.up.1.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.1.conv2.bias', None),
  ('first_stage_model.decoder.up.1.block.2.norm1.weight', None),
  ('first_stage_model.decoder.up.1.block.2.norm1.bias', None),
  ('first_stage_model.decoder.up.1.block.2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.2.conv1.bias', None),
  ('first_stage_model.decoder.up.1.block.2.norm2.weight', None),
  ('first_stage_model.decoder.up.1.block.2.norm2.bias', None),
  ('first_stage_model.decoder.up.1.block.2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.block.2.conv2.bias', None),
  ('first_stage_model.decoder.up.1.upsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.1.upsample.conv.bias', None),
  ('first_stage_model.decoder.up.0.block.0.norm1.weight', None),
  ('first_stage_model.decoder.up.0.block.0.norm1.bias', None),
  ('first_stage_model.decoder.up.0.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.0.conv1.bias', None),
  ('first_stage_model.decoder.up.0.block.0.norm2.weight', None),
  ('first_stage_model.decoder.up.0.block.0.norm2.bias', None),
  ('first_stage_model.decoder.up.0.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.0.conv2.bias', None),
  ('first_stage_model.decoder.up.0.block.0.nin_shortcut.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.0.nin_shortcut.bias', None),
  ('first_stage_model.decoder.up.0.block.1.norm1.weight', None),
  ('first_stage_model.decoder.up.0.block.1.norm1.bias', None),
  ('first_stage_model.decoder.up.0.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.1.conv1.bias', None),
  ('first_stage_model.decoder.up.0.block.1.norm2.weight', None),
  ('first_stage_model.decoder.up.0.block.1.norm2.bias', None),
  ('first_stage_model.decoder.up.0.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.1.conv2.bias', None),
  ('first_stage_model.decoder.up.0.block.2.norm1.weight', None),
  ('first_stage_model.decoder.up.0.block.2.norm1.bias', None),
  ('first_stage_model.decoder.up.0.block.2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.2.conv1.bias', None),
  ('first_stage_model.decoder.up.0.block.2.norm2.weight', None),
  ('first_stage_model.decoder.up.0.block.2.norm2.bias', None),
  ('first_stage_model.decoder.up.0.block.2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.up.0.block.2.conv2.bias', None),
  ('first_stage_model.decoder.norm_out.weight', None),
  ('first_stage_model.decoder.norm_out.bias', None),
  ('first_stage_model.decoder.conv_out.weight', (2, 3, 1, 0)),
  ('first_stage_model.decoder.conv_out.bias', None)],
 'encoder': [('first_stage_model.encoder.conv_in.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.conv_in.bias', None),
  ('first_stage_model.encoder.down.0.block.0.norm1.weight', None),
  ('first_stage_model.encoder.down.0.block.0.norm1.bias', None),
  ('first_stage_model.encoder.down.0.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.0.block.0.conv1.bias', None),
  ('first_stage_model.encoder.down.0.block.0.norm2.weight', None),
  ('first_stage_model.encoder.down.0.block.0.norm2.bias', None),
  ('first_stage_model.encoder.down.0.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.0.block.0.conv2.bias', None),
  ('first_stage_model.encoder.down.0.block.1.norm1.weight', None),
  ('first_stage_model.encoder.down.0.block.1.norm1.bias', None),
  ('first_stage_model.encoder.down.0.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.0.block.1.conv1.bias', None),
  ('first_stage_model.encoder.down.0.block.1.norm2.weight', None),
  ('first_stage_model.encoder.down.0.block.1.norm2.bias', None),
  ('first_stage_model.encoder.down.0.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.0.block.1.conv2.bias', None),
  ('first_stage_model.encoder.down.0.downsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.0.downsample.conv.bias', None),
  ('first_stage_model.encoder.down.1.block.0.norm1.weight', None),
  ('first_stage_model.encoder.down.1.block.0.norm1.bias', None),
  ('first_stage_model.encoder.down.1.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.block.0.conv1.bias', None),
  ('first_stage_model.encoder.down.1.block.0.norm2.weight', None),
  ('first_stage_model.encoder.down.1.block.0.norm2.bias', None),
  ('first_stage_model.encoder.down.1.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.block.0.conv2.bias', None),
  ('first_stage_model.encoder.down.1.block.0.nin_shortcut.weight',
   (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.block.0.nin_shortcut.bias', None),
  ('first_stage_model.encoder.down.1.block.1.norm1.weight', None),
  ('first_stage_model.encoder.down.1.block.1.norm1.bias', None),
  ('first_stage_model.encoder.down.1.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.block.1.conv1.bias', None),
  ('first_stage_model.encoder.down.1.block.1.norm2.weight', None),
  ('first_stage_model.encoder.down.1.block.1.norm2.bias', None),
  ('first_stage_model.encoder.down.1.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.block.1.conv2.bias', None),
  ('first_stage_model.encoder.down.1.downsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.1.downsample.conv.bias', None),
  ('first_stage_model.encoder.down.2.block.0.norm1.weight', None),
  ('first_stage_model.encoder.down.2.block.0.norm1.bias', None),
  ('first_stage_model.encoder.down.2.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.block.0.conv1.bias', None),
  ('first_stage_model.encoder.down.2.block.0.norm2.weight', None),
  ('first_stage_model.encoder.down.2.block.0.norm2.bias', None),
  ('first_stage_model.encoder.down.2.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.block.0.conv2.bias', None),
  ('first_stage_model.encoder.down.2.block.0.nin_shortcut.weight',
   (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.block.0.nin_shortcut.bias', None),
  ('first_stage_model.encoder.down.2.block.1.norm1.weight', None),
  ('first_stage_model.encoder.down.2.block.1.norm1.bias', None),
  ('first_stage_model.encoder.down.2.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.block.1.conv1.bias', None),
  ('first_stage_model.encoder.down.2.block.1.norm2.weight', None),
  ('first_stage_model.encoder.down.2.block.1.norm2.bias', None),
  ('first_stage_model.encoder.down.2.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.block.1.conv2.bias', None),
  ('first_stage_model.encoder.down.2.downsample.conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.2.downsample.conv.bias', None),
  ('first_stage_model.encoder.down.3.block.0.norm1.weight', None),
  ('first_stage_model.encoder.down.3.block.0.norm1.bias', None),
  ('first_stage_model.encoder.down.3.block.0.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.3.block.0.conv1.bias', None),
  ('first_stage_model.encoder.down.3.block.0.norm2.weight', None),
  ('first_stage_model.encoder.down.3.block.0.norm2.bias', None),
  ('first_stage_model.encoder.down.3.block.0.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.3.block.0.conv2.bias', None),
  ('first_stage_model.encoder.down.3.block.1.norm1.weight', None),
  ('first_stage_model.encoder.down.3.block.1.norm1.bias', None),
  ('first_stage_model.encoder.down.3.block.1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.3.block.1.conv1.bias', None),
  ('first_stage_model.encoder.down.3.block.1.norm2.weight', None),
  ('first_stage_model.encoder.down.3.block.1.norm2.bias', None),
  ('first_stage_model.encoder.down.3.block.1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.down.3.block.1.conv2.bias', None),
  ('first_stage_model.encoder.mid.block_1.norm1.weight', None),
  ('first_stage_model.encoder.mid.block_1.norm1.bias', None),
  ('first_stage_model.encoder.mid.block_1.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.block_1.conv1.bias', None),
  ('first_stage_model.encoder.mid.block_1.norm2.weight', None),
  ('first_stage_model.encoder.mid.block_1.norm2.bias', None),
  ('first_stage_model.encoder.mid.block_1.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.block_1.conv2.bias', None),
  ('first_stage_model.encoder.mid.attn_1.norm.weight', None),
  ('first_stage_model.encoder.mid.attn_1.norm.bias', None),
  ('first_stage_model.encoder.mid.attn_1.q.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.attn_1.q.bias', None),
  ('first_stage_model.encoder.mid.attn_1.k.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.attn_1.k.bias', None),
  ('first_stage_model.encoder.mid.attn_1.v.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.attn_1.v.bias', None),
  ('first_stage_model.encoder.mid.attn_1.proj_out.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.attn_1.proj_out.bias', None),
  ('first_stage_model.encoder.mid.block_2.norm1.weight', None),
  ('first_stage_model.encoder.mid.block_2.norm1.bias', None),
  ('first_stage_model.encoder.mid.block_2.conv1.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.block_2.conv1.bias', None),
  ('first_stage_model.encoder.mid.block_2.norm2.weight', None),
  ('first_stage_model.encoder.mid.block_2.norm2.bias', None),
  ('first_stage_model.encoder.mid.block_2.conv2.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.mid.block_2.conv2.bias', None),
  ('first_stage_model.encoder.norm_out.weight', None),
  ('first_stage_model.encoder.norm_out.bias', None),
  ('first_stage_model.encoder.conv_out.weight', (2, 3, 1, 0)),
  ('first_stage_model.encoder.conv_out.bias', None),
  ('first_stage_model.quant_conv.weight', (2, 3, 1, 0)),
  ('first_stage_model.quant_conv.bias', None)]}



